mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("qa.urls")),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/qa/urls.py
from django.urls import path
from .views import *

app_name = "qa"
urlpatterns = [
    path("", QuestionListView.as_view(), name="home"),
    path("user/<str:username>", UserQuestionListView.as_view(), name="user-question"),
    path("question/<int:pk>/", QuestionDetailView.as_view(), name="question-detail"),
    path("question/new/", QuestionCreateView.as_view(), name="question-create"),
    path("question/<int:pk>/update",
         QuestionUpdateView.as_view(), name="question-update"),
    path("question/<int:pk>/delete",
         QuestionDeleteView.as_view(), name="question-delete"),
    path("question/<int:pk>/answer",
         AnswerCreateView.as_view(), name="question-answer"),
    path('question/<int:pk>/like/',
         LikeQuestionView, name='like-question'),
    path('question/<int:pk>/dislike/',
         DislikeQuestionView, name='dislike-question'),
    path('question/<int:pk>/answer/<int:a_pk>/like/',
         LikeAnswerView, name='like-answer'),
    path('question/<int:pk>/answer/<int:a_pk>/dislike/',
         DislikeAnswerView, name='dislike-answer'),
]

mysite/qa/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Question(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.TextField()
    description = models.TextField(null=True, blank=True)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    likes = models.ManyToManyField(
        User, related_name='likes', default=None, blank=True)
    dislikes = models.ManyToManyField(
        User, related_name='dislikes', default=None, blank=True)
    question_image = models.ImageField(
        null=True, blank=True, upload_to='question_pics')

    def __str__(self):
        return self.question

    def get_absolute_url(self):
        return reverse("qa:question-detail", kwargs={"pk": self.pk})

    def total_likes(self):
        return self.likes.count()

    def total_dislikes(self):
        return self.dislikes.count()


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    answer = models.TextField()
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    answer_likes = models.ManyToManyField(
        User, related_name='answer_likes', default=None, blank=True)
    answer_dislikes = models.ManyToManyField(
        User, related_name='answer_dislikes', default=None, blank=True)
    def __str__(self):
        return f' {self.question} : {self.answer} '

    def get_absolute_url(self):
        return reverse("qa:question-detail", kwargs={"pk": self.question.pk})
    
    def total_likes(self):
            return self.answer_likes.count()

    def total_dislikes(self):
        return self.answer_dislikes.count()

mysite/qa/views.py
from django.shortcuts import redirect, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .models import *
from django.contrib.auth.models import User
from django.views.generic import *
from django.urls import reverse
from django.contrib.auth.decorators import login_required


class QuestionListView(ListView):
    model = Question
    template_name = 'qa/home.html'
    context_object_name = 'questions'
    ordering = ['-timestamp']
    paginate_by = 5


class UserQuestionListView(ListView):
    model = Question
    template_name = 'qa/user_question.html'
    context_object_name = 'questions'
    paginate_by = 5

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Question.objects.filter(user=user).order_by('-timestamp')


class QuestionDetailView(DetailView):
    model = Question

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        q = get_object_or_404(Question, pk=self.kwargs.get('pk'))
        answers = Answer.objects.filter(
            question=q).order_by('-timestamp')
        context['answers'] = Answer.objects.filter(
            question=q).order_by('-timestamp')
        total_likes = q.total_likes()
        liked = False
        if q.likes.filter(id=self.request.user.id).exists():
            liked = True
        context['total_likes'] = total_likes
        context['liked'] = liked
        total_dislikes = q.total_dislikes()
        disliked = False
        if q.dislikes.filter(id=self.request.user.id).exists():
            disliked = True
        context['total_dislikes'] = total_dislikes
        context['disliked'] = disliked

        liked_answers = []
        for answer in answers:
            if answer.answer_likes.filter(id=self.request.user.id).exists():
                liked_answers.append(answer)
        context['liked_answers'] = liked_answers

        disliked_answers = []
        for answer in answers:
            if answer.answer_dislikes.filter(id=self.request.user.id).exists():
                disliked_answers.append(answer)
        context['disliked_answers'] = disliked_answers
        return context


class QuestionCreateView(LoginRequiredMixin, CreateView):
    model = Question
    fields = ['question', 'description', 'question_image']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class QuestionUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Question
    fields = ['question', 'description']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def test_func(self):
        question = self.get_object()
        if self.request.user == question.user:
            return True
        return False


class QuestionDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Question
    success_url = "/"

    def test_func(self):
        question = self.get_object()
        if self.request.user == question.user:
            return True
        return False


class AnswerCreateView(LoginRequiredMixin, CreateView):
    model = Answer
    fields = ['answer']
    template_name = 'qa/answer_question.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.question = get_object_or_404(
            Question, pk=self.kwargs.get('pk'))
        return super().form_valid(form)


@login_required
def LikeQuestionView(request, pk):
    q = get_object_or_404(Question, pk=pk)
    if q.likes.filter(id=request.user.id).exists():
        q.likes.remove(request.user)
    else:
        q.likes.add(request.user)
        q.dislikes.remove(request.user)
    return redirect(reverse('qa:question-detail', kwargs={'pk': pk}))


@login_required
def DislikeQuestionView(request, pk):
    q = get_object_or_404(Question, pk=pk)
    if q.dislikes.filter(id=request.user.id).exists():
        q.dislikes.remove(request.user)
    else:
        q.dislikes.add(request.user)
        q.likes.remove(request.user)
    return redirect(reverse('qa:question-detail', kwargs={'pk': pk}))


@login_required
def LikeAnswerView(request, pk, a_pk):
    a = get_object_or_404(Answer, pk=a_pk)
    if a.answer_likes.filter(id=request.user.id).exists():
        a.answer_likes.remove(request.user)
    else:
        a.answer_likes.add(request.user)
        a.answer_dislikes.remove(request.user)
    return redirect(reverse('qa:question-detail', kwargs={'pk': pk}))


@login_required
def DislikeAnswerView(request, pk, a_pk):
    a = get_object_or_404(Answer, pk=a_pk)
    if a.answer_dislikes.filter(id=request.user.id).exists():
        a.answer_dislikes.remove(request.user)
    else:
        a.answer_dislikes.add(request.user)
        a.answer_likes.remove(request.user)
    return redirect(reverse('qa:question-detail', kwargs={'pk': pk}))

mysite/qa/templates/qa/answer_question.html
{%extends "qa/base.html"%}
{%block content%}
    {% load crispy_forms_tags %}
    <div class "content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form_group">
                <legend class="border-bottom-mb-4">Answer</Legend>
                {{form|crispy}}
            </fieldset>
            <div class="form_group">
                <button class="btn btn-outline-info" type="submit">Answer</button>
            </div>
        </form>
    </div>
{%endblock content%}

mysite/qa/templates/qa/base.html
{%load static%}
<!DOCTYPE html>
<html>

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{%static 'qa/main.css'%}">
  <title>Hay Stack</title>
</head>


<body>
  <header class="site-header">


    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
      <div class="container">
        <a class="navbar-brand mr-4" href="{%url 'qa:home'%}#">Hay Stack</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
          aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarToggle">
          <div class="navbar-nav mr-auto">
            <a class="nav-item nav-link" href="{%url 'qa:home'%}">Home</a>
          </div>
          <!-- Navbar Right Side -->
          <div class="navbar-nav">
            {% if  user.is_authenticated %}
                <a class="nav-item nav-link" href="{%url 'qa:question-create'%}">New Question</a> 
                <a class="nav-item nav-link" href="{%url 'profile'%}">Profile</a>
                <a class="nav-item nav-link" href="{%url 'logout'%}">Logout</a>
            {% else %}
                <a class="nav-item nav-link" href="{%url 'login'%}">Login</a>
                <a class="nav-item nav-link" href="{%url 'register'%}">Register</a>
            {% endif %}
        </div>
        </div>
      </div>
    </nav>


  </header>


  <main role="main" class="container">
    <div class="row">
      <div class="col-md-8">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{message.tags}}">
                    {{message}}
                </div>
            {% endfor %}
        {% endif %}
        {% block content %}{% endblock %}
      </div>
      <div class="col-md-4">
        <div class="content-section">
          <h3>Important Updates</h3>
          <p class='text-muted'>Server downtime (if any) is from 10:00 pm to 6:00 am
            <ul class="list-group">
              <a class="list-item list-link" href="#">About</a>
              <a class="list-item " href="#">Contact</a>
            </ul>
          </p>
        </div>
      </div>
    </div>
  </main>


  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous">
  </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous">
  </script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous">
  </script>
</body>

</html>

mysite/qa/templates/qa/home.html
{%extends "qa/base.html"%}
{%block content%}
    {% if  questions%}
        {% for question in questions %}
            <article class="media content-section">
              <img class="rounded-circle article-img" src="{{question.user.profile.image.url}}">
              <div class="media-body">
                <div class="article-metadata">
                  <a class="mr-2" href="{% url 'qa:user-question' question.user.username%}">{{ question.user.username }}</a>
                  <small class="text-muted">{{ question.timestamp }}</small>
                </div>
                <h2><a class="article-title" href="{% url 'qa:question-detail' question.id%}">{{ question.question }}</a></h2>
                <p class="article-content">{{ question.description }}</p>
              </div>
            </article>
        {% endfor %}

        {% if is_paginated %}

          {% if page_obj.has_previous %}
            <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
          {% endif %}

          {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
              <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
              <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
          {% endfor %}

          {% if page_obj.has_next %}
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
          {% endif %}

        {% endif %}

        {% else %}
            <h1>No questions available at the moment</h1>
     {% endif %}
{%endblock content%}

mysite/qa/templates/qa/question_confirm_delete.html
{%extends "qa/base.html"%}
{%block content%}
    <div class "content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form_group">
                <legend class="border-bottom-mb-4">Delete Question</Legend>
                <h2>Are you sure you want to delete the question "{{object.question}}"</h2>
            </fieldset>
            <div class="form_group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{%url 'qa:question-detail' object.id%}">Cancel</a>
            </div>
        </form>
    </div>
{%endblock content%}

mysite/qa/templates/qa/question_detail.html
{%extends "qa/base.html"%}
{%block content%}
<article class="media content-section">
  <img class="rounded-circle article-img" src="{{object.user.profile.image.url}}">
  <div class="media-body">
    <div class="article-metadata">
      <a class="mr-2" href="{% url 'qa:user-question' object.user.username%}">{{ object.user.username }}</a>
      <small class="text-muted">{{ object.timestamp }}</small>
      {% if object.user == user %}
      <div>
        <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'qa:question-update' object.id%}">Update</a>
        <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'qa:question-delete' object.id%}">Delete</a>
      </div>
      {%endif%}
    </div>
    <h2 class="article-title">{{ object.question }}</h2>
    <p class="article-content">{{ object.description }}</p>
    {% if object.question_image %}
    <p> 
      <img class="img-fluid" src={{object.question_image.url}} >
    </p>
    {%endif%}
    <a class="btn btn-secondary " href="{% url 'qa:question-answer' object.id%}">Answer</a>
    <div>
      {%if liked%}
        <a class="btn btn-primary btn-sm mt-1 mb-1" href="{% url 'qa:like-question' object.id%}">
           <img src="/media/upvote.jpg"> ({{total_likes}})
        </a>


      {%else %}
        <a class="btn btn-outline-primary btn-sm mt-1 mb-1" href="{% url 'qa:like-question' object.id%}">
          <img src="/media/upvote.jpg"> ({{total_likes}})
        </a>
      {%endif%}
      &nbsp;
 
      {%if disliked%}
        <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'qa:dislike-question' object.id%}">
          <img src="/media/downvote.jpg"> ({{total_dislikes}})
        </a>
      
      {%else %}
        <a class="btn btn-outline-danger btn-sm mt-1 mb-1" href="{% url 'qa:dislike-question' object.id%}">
          <img src="/media/downvote.jpg"> ({{total_dislikes}})</a>
      {%endif%}
    </div>
  </div>


</article>
<legend class="border-bottom-mb-4">Answers</Legend>
{% if  answers%}
{% for answer in answers %}
<article class="media content-section">
  <img class="rounded-circle article-img" src="{{answer.user.profile.image.url}}">
  <div class="media-body">
    <div class="article-metadata">
      <a class="mr-2" href="{% url 'qa:user-question' answer.user.username%}">{{ answer.user.username }}</a>
      <small class="text-muted">{{ answer.timestamp }}</small>
    </div>
    <p class="article-content">{{ answer.answer }}</p>
    <div>
      {%if answer in liked_answers%}
        <a class="btn btn-primary btn-sm mt-1 mb-1" href="{% url 'qa:like-answer' object.id answer.id%}">
           <img src="/media/upvote.jpg"> ({{answer.total_likes}})
        </a>


      {%else %}
        <a class="btn btn-outline-primary btn-sm mt-1 mb-1" href="{% url 'qa:like-answer' object.id answer.id%}">
          <img src="/media/upvote.jpg"> ({{answer.total_likes}})
        </a>
      {%endif%}
      &nbsp;
 
      {%if answer in disliked_answers%}
        <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'qa:dislike-answer' object.id answer.id%}">
          <img src="/media/downvote.jpg"> ({{answer.total_dislikes}})
        </a>
      
      {%else %}
        <a class="btn btn-outline-danger btn-sm mt-1 mb-1" href="{% url 'qa:dislike-answer' object.id answer.id%}">
          <img src="/media/downvote.jpg"> ({{answer.total_dislikes}})</a>
      {%endif%}
    </div>
  </div>
</article>
{% endfor %}

{% if is_paginated %}

{% if page_obj.has_previous %}
<a class="btn btn-outline-info mb-4" href="?page=1">First</a>
<a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
{% endif %}

{% for num in page_obj.paginator.page_range %}
{% if page_obj.number == num %}
<a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
{% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
<a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
{% endif %}
{% endfor %}

{% if page_obj.has_next %}
<a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
<a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
{% endif %}

{% endif %}

{% else %}
<h1>The question is not yet answered</h1>
{% endif %}
{%endblock content%}

mysite/qa/templates/qa/question_form.html
{%extends "qa/base.html"%}
{%block content%}
    {% load crispy_forms_tags %}
    <div class "content-section">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form_group">
                <legend class="border-bottom-mb-4">Question</Legend>
                {{form|crispy}}
            </fieldset>
            <div class="form_group">
                <button class="btn btn-outline-info" type="submit">Ask</button>
            </div>
        </form>
    </div>
{%endblock content%}

mysite/qa/templates/qa/user_post.html
{%extends "qa/base.html"%}
{%block content%}
    <h1 class="mb-3">Questions by {{view.kwargs.username}} ({{page_obj.paginator.count}})</h1>
    {% if  questions%}
        {% for question in questions %}
            <article class="media content-section">
              <img class="rounded-circle article-img" src="{{question.user.profile.image.url}}">
              <div class="media-body">
                <div class="article-metadata">
                  <a class="mr-2" href="{% url 'qa:user-question' question.user.username%}">{{ question.user.username }}</a>
                  <small class="text-muted">{{ question.timestamp }}</small>
                </div>
                <h2><a class="article-title" href="{% url 'qa:question-detail' question.id%}">{{ question.question }}</a></h2>
                <p class="article-content">{{ question.description }}</p>
              </div>
            </article>
        {% endfor %}

        {% if is_paginated %}

          {% if page_obj.has_previous %}
            <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
          {% endif %}

          {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
              <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
              <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
          {% endfor %}

          {% if page_obj.has_next %}
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
          {% endif %}

        {% endif %}

        {% else %}
            <h1>No questions available at the moment</h1>
     {% endif %}
{%endblock content%}

mysite/qa/templates/qa/user_question.html
{%extends "qa/base.html"%}
{%block content%}
    <h1 class="mb-3">Questions by {{view.kwargs.username}} ({{page_obj.paginator.count}})</h1>
    {% if  questions%}
        {% for question in questions %}
            <article class="media content-section">
              <img class="rounded-circle article-img" src="{{question.user.profile.image.url}}">
              <div class="media-body">
                <div class="article-metadata">
                  <a class="mr-2" href="{% url 'qa:user-question' question.user.username%}">{{ question.user.username }}</a>
                  <small class="text-muted">{{ question.timestamp }}</small>
                </div>
                <h2><a class="article-title" href="{% url 'qa:question-detail' question.id%}">{{ question.question }}</a></h2>
                <p class="article-content">{{ question.description }}</p>
              </div>
            </article>
        {% endfor %}

        {% if is_paginated %}

          {% if page_obj.has_previous %}
            <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
          {% endif %}

          {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
              <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
              <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
          {% endfor %}

          {% if page_obj.has_next %}
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
          {% endif %}

        {% endif %}

        {% else %}
            <h1>No questions available at the moment</h1>
     {% endif %}
{%endblock content%}